services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - 9093:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ${PWD}/data/postgres:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ${PATH_TO_NAS_PROMSTACK}/prometheus/prometheus.yml/:/etc/prometheus/prometheus.yml
      - ${PATH_TO_NAS_PROMSTACK}/prometheus/prometheus/:/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - 9091:3000
    volumes:
      - ${PATH_TO_NAS_PROMSTACK}/grafana/grafana/:/var/lib/grafana
  metrics-server:
    image: ghcr.io/velvetreactor/metrics:latest
    ports:
      - ${METRICS_SERVER_PORT}:8080
    environment:
      - MY_BUDGET_ID=${MY_BUDGET_ID}
      - YNAB_TOKEN=${YNAB_TOKEN}
